export const initialExerciseData = [
  {
    name: "Barbell Squats",
    id: 1,
    restTimer: 90,
    metrics: [
      {
        name: "weight",
        adaptive: true,
        inputBar: "NumberIncrementBar",
        step: 5,
        default: 185,
        units: "lbs",
      },
      {
        name: "reps",
        adaptive: true,
        inputBar: "NumberIncrementBar",
        step: 1,
        default: 5,
        units: "",
      },
    ],
  },
  {
    name: "Barbell Row",
    id: 2,
    restTimer: 90,
    metrics: [
      {
        name: "weight",
        adaptive: true,
        inputBar: "NumberIncrementBar",
        step: 5,
        default: 135,
        units: "lbs",
      },
      {
        name: "reps",
        adaptive: true,
        inputBar: "NumberIncrementBar",
        step: 1,
        default: 5,
        units: "",
      },
    ],
  },
  {
    name: "Bench Press",
    id: 3,
    restTimer: 90,
    metrics: [
      {
        name: "weight",
        adaptive: true,
        inputBar: "NumberIncrementBar",
        step: 5,
        default: 135,
        units: "lbs",
      },
      {
        name: "reps",
        adaptive: true,
        inputBar: "NumberIncrementBar",
        step: 1,
        default: 5,
        units: "",
      },
    ],
  },
  {
    name: "Overhead Press",
    id: 4,
    restTimer: 90,
    metrics: [
      {
        name: "weight",
        adaptive: true,
        inputBar: "NumberIncrementBar",
        step: 5,
        default: 105,
        units: "lbs",
      },
      {
        name: "reps",
        adaptive: true,
        inputBar: "NumberIncrementBar",
        step: 1,
        default: 5,
        units: "",
      },
    ],
  },
  {
    name: "Deadlift",
    id: 5,
    restTimer: 90,
    metrics: [
      {
        name: "weight",
        adaptive: true,
        inputBar: "NumberIncrementBar",
        step: 5,
        default: 190,
        units: "lbs",
      },
      {
        name: "reps",
        adaptive: true,
        inputBar: "NumberIncrementBar",
        step: 1,
        default: 5,
        units: "",
      },
    ],
  },
  {
    name: "Pushups",
    id: 6,
    restTimer: 60,
    metrics: [
      {
        name: "reps",
        adaptive: true,
        inputBar: "NumberIncrementBar",
        step: 1,
        default: 15,
        units: "",
      },
    ],
  },
  {
    name: "Pullups",
    id: 7,
    restTimer: 90,
    metrics: [
      {
        name: "reps",
        adaptive: true,
        inputBar: "NumberIncrementBar",
        step: 1,
        default: 7,
        units: "",
      },
    ],
  },
  {
    name: "Leg Press",
    id: 8,
    restTimer: 90,
    metrics: [
      {
        name: "weight",
        adaptive: true,
        inputBar: "NumberIncrementBar",
        step: 1,
        default: 200,
        units: "lbs",
      },
      {
        name: "reps",
        adaptive: true,
        inputBar: "NumberIncrementBar",
        step: 1,
        default: 5,
        units: "",
      },
    ],
  },
  {
    name: "Swimming Laps",
    id: 9,
    restTimer: 300,
    metrics: [
      {
        name: "laps",
        adaptive: true,
        inputBar: "NumberIncrementBar",
        step: 1,
        default: 8,
        units: "",
      },
    ],
  },
];
